config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/about', to: 'pages#about'
  resources :users
  get '/signup', to: 'users#new'

  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  resources :sessions, only: :create
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  #Basic Validations
  validates :name, presence: true, length: { maximum: 50 }
  #To validate correct email structure
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                                    format: { with: EMAIL_REGEX },
                                    uniqueness: { case_sensetive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_nil: true

  has_many :active_relationships, class_name: "Relationship",
                                foreign_key: "follower_id",
                                dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower 


  #Follow a user
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  #Unfollow a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  #Return true if the current user if following the other user
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def logged_in_user
    unless logged_in?
      flash[:info] = "Please login first."
      redirect_to login_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    redirect_back(fallback_location: request.referer)
  end

  def destroy
    @user = Relationship.find(params[:id]).followed
    current_user.unfollow(@user)
    redirect_back(fallback_location: request.referer)
  end
end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      #login user
      log_in(user)
      flash[:success] = "Successfully logged in."
      redirect_to root_url
    else
      #redirect back to the login_url
      flash[:danger] = "Invalid Credentials"
      redirect_to login_url 
    end
  end

  def destroy
    log_out
    flash[:success] = "Successfully logout."
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, except: [:new, :create]
  before_action :correct_user, only: :edit

  def index
    @users = User.paginate(page: params[:page], per_page: 10).order(created_at: :desc)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Successfully Created a Account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile Updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      user = User.find(params[:id])
      if user != current_user
        flash[:danger] = "You are not authorized."
        redirect_to root_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
    def profile_image(user, size)
      #generate the hex token
      gravatar_id = Digest::MD5::hexdigest(user.email)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: user.name, class: "rounded-circle #{size}")
    end
  end
  

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
    <% flash.each do |type, msg| %>
        <div class="mt-4 alert alert-<%= type %> alert-dismissible fade show" role="alert">
            <strong><%= msg %></strong>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">AWESOMEBLOG</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About Us", about_path, class: "nav-link" %>
                </li>
               
                <% if logged_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <%= current_user.name %> 
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
                            <%= link_to "Edit profile", edit_user_path(current_user), class: "dropdown-item" %>
                            <%= link_to "Users", users_path, class: "dropdown-item" %>
                            <div class="dropdown-divider"></div>
                            <%= link_to "Logout", logout_path, class: "dropdown-item"%>
                        </ul>
                    </li>
                <% else %>
                     <li class="nav-item">
                        <%= link_to "Signup", signup_path, class: "nav-link"%>
                    </li>
                    <li class="nav-item">
                        <%= link_to "Log in", login_path, class: "nav-link" %>
                    </li>
                <% end %>
                
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= yield(:title) %> | Awesome Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render "layouts/navbar" %>
    <div class="container">
        <%= render "layouts/flash_messages"%>
        <%= yield %>
    </div>
</body>

</html>

app/views/pages/about.html.erb
<% provide(:title, 'About') %>
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<% provide(:title, 'Home') %>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        This for contains errors.
    </div>
    <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build, remote: true) do |f| %>
    <%= hidden_field_tag :followed_id, @user.id %>
    <%= f.submit "Follow", class: "btn btn-primary"%>
<% end%>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
    <% if current_user.following?(@user)%>
        <%= render "unfollow"%>
    <% else %>
        <%= render "follow"%>
    <% end %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
    <%= render 'shared/error_messages', object: f.object%>
    <div class="mb-3">
        <%= f.text_field :name, class:"form-control", placeholder: "Name" %>
    </div>
    <div class="mb-3">
        <%= f.email_field :email, class:"form-control", placeholder: "Email"%>
    </div>
    <div class="mb-3">
        <%= f.password_field :password, class:"form-control", placeholder: "Password"%>
    </div>
    <div class="mb-3">
        <%= f.password_field :password_confirmation, class:"form-control", placeholder: "Password Confirmation"%>
    </div>
    <%= f.submit btn_msg, class: "btn btn-primary w-100"%>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed_id: @user.id),
    html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit Profile') %>
<div class="col-4 mx-auto">
    <h1 class="text-center mt-4">Edit Profile</h1>
    <%= render "form", btn_msg: "Update Profile" %>
</div>

app/views/users/index.html.erb
<% provide(:title, "Users")%>
<h1 class="text-center mt-4">All Users</h1>
<div class="row">
    <% @users.each do |user| %>
        <div class="col-6">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <%= profile_image(user, "profile-medium")%>
                        </div>
                        <div class="col-10">
                            <h6><%= link_to user.name, user_path(user) %></h6>
                            <span><%= user.email %></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    <% end %>
    <div class="pagination justify-content-center mt-4">
        <%= will_paginate @users %>
    </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign-up') %>
<div class="col-4 mx-auto">
    <h1 class="text-center mt-4">Sign up</h1>
    <%= render "form", btn_msg: "Create a new account" %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name)%>
<div class="row mt-4">
    <div class="col-4">
        <div class="card">
            <div class="card-header">
                User Information
            </div>
            <div class="card-body text-center">
                <%= profile_image(@user, "profile-medium")%>
                <h5><%= @user.name%></h5>
                <p><%= @user.email %></p>
                <%= render "follow_form"%>
            </div>
        </div>
    </div>

    <div class="col-8">
        <div class="card">
            <div class="card-header">
                Activity Feeds
            </div>
            <div class="card-body">
            </div>
        </div>
    </div>
</div>